import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/globals.css";

import RootHeader from "./components/RootHeader";
import RootFooter from "./components/RootFooter";
import NewBar from "./components/NewBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    description: "Hello Nextjs !!!",
    template: "DaeLim.com - %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <RootHeader />
        <NewBar />
        <main>{children}</main>
        <RootFooter />
      </body>
    </html>
  );
}
